[build-system]
requires = ["setuptools", "wheel", "torch"]
build-backend = "setuptools.build_meta"

[project]
name = "diff-surfel-rasterization"
version = "0.0.1"
dependencies = []
requires-python = ">=3.8"
authors = []
maintainers = []
description = ""
readme = "README.md"